### ISSUE TITLE
Automatically generating methods.json from trakt.tv API docs

### ISSUE THREAD

**Issue by janpio** [vankasteelj/trakt.tv#42]
Hey, do you generate the methods.json manually right now? Do you get all the information straight from the trakt.tv API docs?

I created a (super ugly) PHP script that parses the .apib file of the trakt.tv API docs and creates its own API docs: http://yatsa.betamo.de/trakt-api/ With a little bit of time investment I think I could probably generate the methods.json automatically. Do you think this is worth it?

(If you look at the link please note that this is generating from a forked version of the .apib right now that has my own changes for testing things out. For methods.json generation this of course would use the original one.)

**Comment by vankasteelj** [comment]
It's manual because I have control over things. the documentation is not done well enough to my taste, for exemple on the official api, `username` are called `id` which makes absolutely no sense. Plus I can tweak and regroup the methods, like `comments.get`, `comments.add` and `comments.delete` instead of a unusable `comments` (without `.get`) and then `.add`/`.delete`

To update, I track the changes on the [changelog](https://apiblog.trakt.tv/api-changelog-9f4041819718). Procedural is good, but when you need an exception on almost half of the autogenerated methods, it's more a pain than an improvement.

**Comment by janpio** [comment]
I feel your pain. Makes sense, so no automatic generation for now.
